### ISSUE TITLE
Banker

### ISSUE THREAD

**Issue by North58Man** [ZehenForever/mqcollect#1]
Could you add the ability to put collect items of characters into their bank.

**Comment by ZehenForever** [comment]
This is a great feature request.  Let me add this to my list.

**Comment by ZehenForever** [comment]
Actually this was easy to implement.  I added a new command:  `/give bank`.  From any character, move all of their defined items to the bank. NB: currently requires the bank window to already be open.

**Comment by ZehenForever** [comment]
Implemented for the current character.
