### ISSUE TITLE
e3bots

### ISSUE THREAD

**Issue by North58Man** [ZehenForever/mqcollect#2]
I can not get 'collect e3bots' to work. Is it implimented yet? Is it on your todo list?

**Comment by ZehenForever** [comment]
It is already implemented but it needs a newer version of E3 since it leverages the `mq.TLO.MQ2Mono.Query('e3,E3Bots.ConnectedClients')()` query.

**Comment by North58Man** [comment]
CoolSent from my Galaxy
-------- Original message --------From: ZehenForever ***@***.***> Date: 2024-05-13  5:31 p.m.  (GMT-08:00) To: ZehenForever/mqcollect ***@***.***> Cc: North58Man ***@***.***>, Author ***@***.***> Subject: Re: [ZehenForever/mqcollect] e3bots (Issue #2) 
It is already implemented but it needs a newer version of E3 since it leverages the mq.TLO.MQ2Mono.Query('e3,E3Bots.ConnectedClients')() query.

**Comment by North58Man** [comment]
Do you know if the feature is currently on the wish list for E3N, I have
presumed this lua is suppose to work with E3N and not E3 version 9.

**Comment by GeneStevens** [comment]
You're correct:  it is for E3N only.
